#!/usr/bin/with-contenv bash
set -euo pipefail

mkdir -p /data/grafana \
         /data/logs \
         /data/plugins \
         /share/energymanager/grafana/dashboards \
         /share/energymanager/grafana/datasources

if getent passwd grafana >/dev/null 2>&1; then
  chown -R grafana:grafana /data /share/energymanager/grafana || true
else
  chown -R 472:472 /data /share/energymanager/grafana || true
fi
